spring:
  application:
    name: order
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password:
      url: jdbc:mysql://127.0.0.1/spring_cloud_sell?characterEncoding=utf-8&userSSL=false
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081
env: dev
rabbitmq:
  host: 192.168.165.169
  port: 5672
  username: guest
  password: guest
